### ISSUE TITLE
include prometheus and grafana for monitoring and insights

### ISSUE THREAD

**Issue by mpo-vliz** [MareGraph-EU/ldes-testbed-docker#8]
with this it should be possible to have some insight into ldes-client output in a graphical way
leading to graphs like this:

![Image](https://github.com/user-attachments/assets/8c4dea75-db70-4639-84e8-3109fb00dec2)

work seems to involve
- [ ] adding grafana and prometheus to the docker stack ?
- [ ] setting ldio to expose stats
- [ ] setting prometheus to grab those stats (targets?)
- [ ] setting grafana to visualise what is in prometheus

some resources found that might help:
- docker hub images to use
  - https://hub.docker.com/r/prom/prometheus
  - https://hub.docker.com/r/grafana/grafana-oss
- see docs at https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/2.12.0/ldio/index --> however: 
  - unclear where the exposed stats can be found portnumber? path?
  - unclear in what yml files the suggested prometheus enabling should go? springdoc vs management?
- https://grafana.com/docs/grafana/latest/getting-started/get-started-grafana-prometheus/
- colleagues at vliz have some examples and experience around

**Comment by mpo-vliz** [comment]
**update**

digged back into the docs at https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/2.12.0/ldio/index and tried out some combos of possible intended good configs

finally ended up with 

```yaml
springdoc:
  logging:
    level:
      be.vlaanderen.informatievlaanderen: DEBUG
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
```

results in something that looks like proper managament data exposure to use at `http://localhost:8080/actuator/prometheus`  (default port on local docker )

**Comment by mpo-vliz** [comment]
**update** 
Found the missing / unclear parts through 
- re-iterating over the docs in https://informatievlaanderen.github.io/VSDS-Linked-Data-Interactions/2.12.0/ldio/index and 
- just trying out some variants and assumptions

Apparently the correct syntax to be pushed in the application yaml for ldio-wokrbench is to combine both `springdoc` and `management` keys:
```yaml
springdoc:
  logging:
    level:
      be.vlaanderen.informatievlaanderen: DEBUG
management:
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
```

after that the ldio-workbench system is exposing both the default `/actuator/heath` as well as the `/actuator/prometheus` management data on the same LDIO_PORT available for the admin-rest-api.

as soon as ldio pipe is started the exposure also starts showing ldio related counts

![Image](https://github.com/user-attachments/assets/c1ffb087-2485-4287-a18b-4f04c7ed7c73)

**Comment by mpo-vliz** [comment]
to be investigated later -- here some standard docker-compose yml stuff that shoud get the full stack completed:
```yaml
prometheus:
    image: prom/prometheus:latest
    container_name: ldes-test-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '0.75GB'
        reservations:
          cpus: '0.50'
          memory: '0.5GB'


  grafana:
    container_name: ldes-test-grafana
    image: grafana/grafana:main
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PWD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://grafana:3000/api/health"]
      interval: 12s
      timeout: 3s
      retries: 20
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '0.75GB'
        reservations:
          cpus: '0.50'
          memory: '0.5GB'
```

to be used together with the prometheus.yml file that looks like this:
```yaml

global:
  scrape_interval: 1m

scrape_configs:
    - job_name: 'ldio-workbench'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ldio-workbench:8080']
```

what seems missing though is how grafana links to prometheus in this setup...
